### ISSUE TITLE
Tracking - add Facebook pixel

### ISSUE THREAD

**Issue by vsalvino** [coderedcorp/coderedcms#128]
Similar to our built in google analytics tracking, which is activated by adding a UA- number, let's implement facebook pixel tracking, which would also be activated by adding a pixel id.

This should be added to the Tracking settings, and as such, we should probably change the icon to something more generic than the Google G.

https://developers.facebook.com/docs/facebook-pixel/implementation 

As a side note, I can see us implementing many different tracking services in the future. Maybe each tracking service should use an include HTML template to keep them manageable without the base.html template getting too big.

**Comment by vsalvino** [comment]
I'm going to close this for now. It is easy enough to add custom tracking codes to `base.html`. I think having the ability to support multiple common tracking codes would be something we should evaluate as a built-in feature or possibly a hook of some sort.

**Comment by bahoo** [comment]
I'm into this, but late to the party apparently!

I wonder too, like — I'm seeing a ton of `coderedcms_*settings` tables; could those be consolidated down into one? Maybe borrowing from `wagtailcore_pagerevision` 's convention of just dropping all the relevant info into a JSON field ?

Tidiness of database tables alone probably isn't enough, but might that lower the barrier for adding more types of settings ( & make tickets like this smaller / easier )? Becoming a row, or even just a field value, instead of a brand new table? Effort involved to get there is probably non-trivial, but if that seems like a worthwhile direction, I'm happy to look into it.

**Comment by vsalvino** [comment]
The settings are implemented using Wagtail's settings feature, as recommended by their documentation: https://docs.wagtail.io/en/v2.8.1/reference/contrib/settings.html

The alternative would be to put all of our settings into one huge panel. Which would be doable, but difficult to find what you need.

Specifically for API keys, we did want to figure out a way to clean that up and make the more dynamic, rather than having one key per settings panel. It would probably involve use of a Wagtail hook to dynamically display them.

Alternatively, it would also be nice for us to implement all of the major tracking codes, but since we do not use them all, it would require contribution from people who do use them regularly.
