### ISSUE TITLE
Django 3 support

### ISSUE THREAD

**Issue by JorneVL** [coderedcorp/coderedcms#290]
With the latest version of Wagtail, Django 3.0 is supported.
Codered CMS and related packages still uses parts that are deprecated or removed in Django 3.0.
Pull request #148 solves a part of this.

#### Additional context
I have created a local clone where I have fixed some parts about Django 3.0
But there are two packages that still uses removed parts of Django.
So I can't test the code.

- django-eventtools uses python_2_unicode_compatible
- wagtail-cache uses lru_cache

Wagtail-cache is maintained by Codered Corp, but Eventtools hasn't had a commit since 14 Aug 2018.
What is the best way to proceed this upgrade?

**Comment by vsalvino** [comment]
Thanks for checking on this. I think the upcoming Wagtail 2.8 will support Django 3.0, so this is a timely issue.

I imagine the fixes shouldn't be too bad in coderedcms - but I think pull request #148 is somewhat abandoned. If you have a fork that fixes Django 3.0 issues, a pull request would be much appreciated!

We can handle upgrading wagtail-cache.

For django-eventtools, that will require more investigation. Hopefully they will accept a patch. Otherwise we (or somebody) would have to fork django-eventtools, which I would like to avoid at all costs.

**Comment by JorneVL** [comment]
I have created PR #291.
I have created an issue for Eventtools: https://github.com/gregplaysguitar/django-eventtools/issues/32

**Comment by vsalvino** [comment]
Fixed by #291
