### ISSUE TITLE
Article Page with responsive grid add author field, caption etc.

### ISSUE THREAD

**Issue by zafon18** [coderedcorp/coderedcms#296]
First of all, I would like to thank you for a good job.
I have a question, is it possible to add a responsive grid for an article page?
Regards.

This is template page:
`https://github.com/coderedcorp/coderedcms/blob/master/coderedcms/templates/coderedcms/pages/article_page.html`

**Comment by vsalvino** [comment]
It is possible, but by default we provide a simpler body without grid. This is to help enforce the pattern that an "article" really is an "article", it will not contain additional visual elements.

In your case, I would recommend making a custom page type based on CoderedWebPage if you want the grid.

```python
from coderedcms.models import CoderedWebPage

class MyCustompage(CoderedWebPage):
    ...
```

Otherwise, you can override the ArticlePage to include a grid... just keep in mind that if you make this change it will probably wipe out any content on existing article pages since you will be drastically changing the streamfield of the page body.

```python
from coderedcms.blocks import LAYOUT_STREAMBLOCKS

ArticlePage(CoderedArticlePage):
    body = StreamField(LAYOUT_STREAMBLOCKS, null=True, blank=True)
````

There are other types of pre-defined layouts in `codredcms.blocks`, see: https://github.com/coderedcorp/coderedcms/blob/master/coderedcms/blocks/__init__.py

**Comment by zafon18** [comment]
Great, thanks for your help. I listened to your advice and created a new index for articles with a grid (parent) and an article with a grid (child). Everything works fine, but there is a sort problem with the "Display publish date, newest first" setting. I made changes at website/models.py
This is code
`class ArticlePageGrid(CoderedWebPage):
    """
    Article, suitable for news or blog content.
    """
    class Meta:
        verbose_name = 'ArticleGrid'
        ordering = ['-first_published_at',]

    # Only allow this page to be created beneath an ArticleIndexPage.
    parent_page_types = ['website.ArticleIndexPageGrid']

    template = 'coderedcms/pages/article_page.html'
    amp_template = 'coderedcms/pages/article_page.amp.html'
    search_template = 'coderedcms/pages/article_page.search.html'

class ArticleIndexPageGrid(CoderedArticleIndexPage):
    """
    Shows a list of article sub-pages.
    """
    class Meta:
        verbose_name = 'Article Landing Page Grid'

    # Override to specify custom index ordering choice/default.
    index_query_pagemodel = 'website.ArticlePageGrid'

    # Only allow ArticlePages beneath this page.
    subpage_types = ['website.ArticlePageGrid']

    template = 'coderedcms/pages/article_index_page.html'`

Shouldn't I edit website/models/page_models.py?
Thanks again for your help 🍺

**Comment by vsalvino** [comment]
Everything looks good, except one thing to note about the ordering. The default ordering is selectable in the wagtail admin on your ArticlePageGrid Page > LAYOUT tab, there is a dropdown for child page ordering. If you set it to "default" it will use the Meta ordering on your model. Otherwise you can override it in the LAYOUT tab.

**Comment by zafon18** [comment]
Great, everything works as it should. Subject to close.
Best Regards!

**Comment by zafon18** [comment]
How do you add the author, caption, date public etc fields to new page models?

```python
class ArticlePageGrid(CoderedWebPage):
    """
    Article, suitable for news or blog content.
    """
    class Meta:
        verbose_name = 'ArticleGrid'
        ordering = ['-first_published_at',]

    # Only allow this page to be created beneath an ArticleIndexPage.
    parent_page_types = ['website.ArticleIndexPageGrid']

    template = 'coderedcms/pages/article_page.html'
    amp_template = 'coderedcms/pages/article_page.amp.html'
    search_template = 'coderedcms/pages/article_page.search.html'
```

How do you add the author, caption, date public etc fields to new page models, and can you expand with more fields?

Thanks for the hints

**Comment by zafon18** [comment]
I add it through
```python 
    date = models.DateField("Post date")
    author = models.CharField(max_length=250)
```
```python
 search_fields = Page.search_fields + [
        index.SearchField('author '),
        index.SearchField('body'),
    ]

    content_panels = Page.content_panels + [
        FieldPanel('date'),
        FieldPanel('author '),
    ]
```
Is this correct?
