### ISSUE TITLE
NavBar: Link that change based on user status.

### ISSUE THREAD

**Issue by ashrafZolkopli** [coderedcorp/coderedcms#323]
Hi CodeRedCorps Team,

I am wondering how do you create a NavBar Link that can change based on the user status?

quick example would be a signup link and a login link when the user have not been authenticated and when he/she had been authenticated, the link change to profile and logout link.

currently what im doing is to attach my own navbar on top of your navbar, would be great if this is able to be done without me manually change the template

**Comment by vsalvino** [comment]
This question also recently came up on our slack channel (https://wagtail.io/slack, #coderedcms channel)

You would inevitably have to customize a template. I would recommend overriding the `coderedcms/snippets/navbar.html` template, and from there you can include any necessary template tags or logic needed.

Unfortunately the navbar and other snippets are difficult to customize, due to this issue: #56

**Comment by ashrafZolkopli** [comment]
> This question also recently came up on our slack channel (https://wagtail.io/slack, #coderedcms channel)
> 
> You would inevitably have to customize a template. I would recommend overriding the `coderedcms/snippets/navbar.html` template, and from there you can include any necessary template tags or logic needed.
> 
> Unfortunately the navbar and other snippets are difficult to customize, due to this issue: #56

@vsalvino Thanks man for the reply, I thought so too... anyway its ok, As of right now I am doing the customization in the snippet too...

seriously though didnt thought i would get a reply this fast..
