### ISSUE TITLE
Support SVG logo

### ISSUE THREAD

**Issue by adminBTI** [coderedcorp/coderedcms#382]
Right now, I cannot use SVG file as site logo. Please support this. Also, it would be nice to be able to upload SVG images and use them in pages too

**Comment by vsalvino** [comment]
I think this is a Wagtail (or more likely Willow) limitation... can you try creating a fresh Wagtail project (not coderedcms) and try uploading an SVG image in the wagtail admin?

**Comment by adminBTI** [comment]
SVG is not supported by Wagtail either. This extension is supposed to do it: https://github.com/City-of-Helsinki/wagtail-svgmap
But I haven't tested it. Even if it did, it would only allow uploaded SVG images. The Issue tracker discussion for Wagtail recommends using SVG file as a document include.

It would be nice if Coderedcms supported logo to be an SVG file in the settings menu.

**Comment by vsalvino** [comment]
I agree SVG support would be nice. Please file an issue with Wagtail (if there isn't already one) as that is the place SVG support will need to happen. Since SVGs are text-based and not binary files, all of the rendition operations would have to be skipped over when handling SVG-based images, so I imagine it is a big undertaking to implement.

For now my best recommendation would be to generate a high quality PNG (300 dpi) from your SVG and use that as the logo. That should look equally sharp on any device. If you do need SVG, override `coderedcms/snippets/navbar.html` template and replace the logo in there (using either a static file, or wagtail Document).
