### ISSUE TITLE
Form Captcha

### ISSUE THREAD

**Issue by corysutyak** [coderedcorp/coderedcms#4]
Ability to enable a caption on forms.

This could potentially be implemented as either a form field, or at the page level. Potentially useful library https://github.com/praekelt/django-recaptcha

**Comment by vsalvino** [comment]
Have done a little research into preventing spam form submissions. I would really like to avoid using a recaptcha, or Google's I am not a robot, because those are both frustrating experiences, and also require an API key or 3rd party integration. An ideal anti-spam solution would be open source, run locally on the website, and require minimal or no user interaction.

One of the most common simple solutions is having a normal text input that serves as a honeypot. This field would be hidden from the user, through either javascript or css. If the honeypot text input is submitted and is NOT empty, then you know it was an automated spam submission. My only qualm with this approach is that it might potentially mess with screen readers.

I might implement this on a client site that gets a lot of spam and see how effective it is. Open to other suggestions as well.

**Comment by emanresu92** [comment]
django-simple-captcha ( https://github.com/mbi/django-simple-captcha ) does not use Google captcha, Akismet etc. It also supports simple math captcha

**Comment by vsalvino** [comment]
The spam is an issue we need to address, many sites are falling victim to high spam count. Queuing this up for next release.

**Comment by vsalvino** [comment]
I have been using this honeypot technique on a couple sites and it has worked extremely well, catching 100% of the spam so far with no false positives. It should be decently friendly to screen readers, text-only browsers, or edge-cases where someone actually sees the hidden input, since it is labeled as sort of a Turing test.

In form_page.html:
```html
<form ... >
{% csrf_token %}
<div style="overflow:hidden;width:0;height:0;" aria-hidden="true">
    <label for="cr-decoy-comments">Leave this blank if you're a human</label>
    <textarea rows="1" name="cr-decoy-comments" id="cr-decoy-comments"></textarea>
</div>
... rest of form ...
```

Then on the FormPage serve method:
```python
def serve(self, request, *args, **kwargs):
    if request.method == 'POST' and request.POST.get("cr-decoy-comments", None):
        # Log that a spam submission was detected.
        logger.error(
            "Spam form submission",
            extra={"request": request},
        )
        # Tell form to just render the page normally.
        request.method = 'GET'
    return super().serve(request, *args, **kwargs)
```

Most likely I'm thinking we would want to inject the HTML into the actual django form, which might be complicated. Alternatively we could make a template tag like `{% antispam %}` or something. On the serve method, the checking could be toggled on/off by an attribute on the model in the settings tab (on by default).

For false positives, I'm not sure how we want to handle it. In the script above I am just firing `logger.error` to manually review them via email. A couple ideas:
* When a spam is detected, redirect to the form page with a 200 status code but containing an error message that the submission was not successful.
* Store the spams as FormSubmission objects with an additional "spam" attribute set for easy manual filtering and removal. Do not send an admin email notification or a confirmation email.
* Log it as a warning or info level, and document that if you want to review them you will have to set the log to write to file at that specific level. We could provide an example in the project template settings.

**Comment by emanresu92** [comment]
With this honeypot technique, can we keep a cache of spammer IP addresses? That way, we can share it with community

**Comment by vsalvino** [comment]
@emanresu92 I think the approach we are going to take will be to log the full request info from spam submissions via the python logger. So you would be able to capture that logging however you see fit, or you could override the function to provide your own logic.
