### ISSUE TITLE
Remove formatted code block from default streamfield

### ISSUE THREAD

**Issue by vsalvino** [coderedcorp/coderedcms#43]
Topic of debate: the streamfield is extremely heavy when adding nested blocks. I'm thinking we could probably remove the Formatted Code block, since it is actually a bit if a pig due to the language selector dropdown, and is the least likely to be used by 99% of websites.

This would be something we would keep in the cms, just remove it from the default blocks on a web page. So it would give us another opportunity to figure out a clean and easy way for devs to add additional blocks to the streamfield without too much code.

I already have an idea, similar to how we have variables for CONTENT_BLOCKS etc, we could allow the user to override CONTENT_BLOCKS so they can "plug in" their desired blocks, and all the WebPages would automatically pull from the overridden CONTENT_BLOCKS (would still require a migration, but seems relatively painless otherwise). This would function similar to the CODERED_THEME_* settings.

**Comment by FlipperPA** [comment]
If you head in this direction, we could use `wagtailcodeblock` as an option for folks. It uses PrismJS rather than Pygments, so it provides real-time syntax highlighting preview in the Wagtail editor interface. The set of languages given is set by a Django setting; if not set, it defaults to a typical set for Python programmers.

https://github.com/FlipperPA/wagtailcodeblock

**Comment by vsalvino** [comment]
Let's completely remove the `CodeBlock` from coderedcms, and therefore remove pygments from the setup.py requirements. That should reduce a lot of overhead and migration problems.

Custom blocks can be added to the `body` of pages in `website/models.py` until we find a more dynamic approach of adding them in.

**Comment by vsalvino** [comment]
Fixed by PR #50
