### ISSUE TITLE
(security) An login user can access local files on coderedcms server 

### ISSUE THREAD

**Issue by ksg97031** [coderedcorp/coderedcms#448]
#### Describe the bug
The below code is accepting any url format.
https://github.com/coderedcorp/coderedcms/blob/49673f2bec0ad70f3ea2e04b32a5fce9e63cb916/coderedcms/urls.py#L21-L25

And then passing path as an argument is a weakness to path traversal attack.
https://github.com/coderedcorp/coderedcms/blob/dev/coderedcms/views.py#L109-L123

#### Steps to reproduce
Access the protected file with encoded url '..%2f'
http://localhost:8000/protected/..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2fetc/passwd

![image](https://user-images.githubusercontent.com/6715194/134806330-ee7f3601-752b-48c8-8b51-cb6ad9c78a28.png)

**Comment by vsalvino** [comment]
Thanks for reporting! This will be fixed in 0.22.3

Luckily, the impact of this is lessened since this URL only works for logged-in users.

And as a reminder to anyone reading this: you SHOULD NOT run your web server with root permission (or any account with filesystem permissions outside your application directory).
