### ISSUE TITLE
Scheduled release version with Wagtail 4 support ?

### ISSUE THREAD

**Issue by redwired** [coderedcorp/coderedcms#560]
Hi,

New to wagtail/coderedcms, I tested and adopted it as my future default CMS platform.

I've started developing with v1.0.*, but realized we are very close to get support for wagtail 4

So my question is : can we expect a release soon ?

Also, should I finish my first site using 1.0.3 (with pip install) and then upgrade when WT4 support will be released ? Or is it preferable to start using the 'dev' branch right now until next stable release ? 

I've planned to go on production in the next few days (I'm configuring my site and and creating my pages right now), but I would like the future upgrade to WT4 to be the least painful as possible.

Thanks for all your incredible work.

**Comment by vsalvino** [comment]
Because we run hundreds of CRX sites, the upgrades are designed to be as easy and painless as possible. The Wagtail 4 upgrade with CRX in particular is going to be very easy based on my initial testing. 

The dev branch is mostly stable, however I would recommend avoiding it for your production site unless you absolutely need a feature from Wagtail 4. That being said, we do appreciate people testing out the dev branch and reporting bugs/feedback.

The new release is coming within the next couple days. We just have a bit more tech debt to take care of.
