### ISSUE TITLE
CSS Issues in Wagtail Admin

### ISSUE THREAD

**Issue by FlipperPA** [coderedcorp/coderedcms#61]
The CSS included in for the Wagtail admin creates some weird horizontal spacing when integrated with an existing site. For example, have a look at the horizontal row (including Day of Week):

Without CodeRed (good):

![image](https://user-images.githubusercontent.com/68164/50177287-9c94e400-02cf-11e9-97b9-dea5ad684d65.png)

With CodeRed (bad - dropdowns obscured by the bar):

![image](https://user-images.githubusercontent.com/68164/50177438-01e8d500-02d0-11e9-91ea-85db1e60edf6.png)

The `content_panels` declaration is as follows; `FieldRowPanel` seems problematic with the CSS:

```python
    content_panels = Page.content_panels + [
        FieldPanel("group"),
        FieldRowPanel(
            [
                FieldPanel("day_of_week"),
                FieldPanel("start_time"),
                FieldPanel("end_time"),
            ]
        ),
        FieldPanel("types", widget=CheckboxSelectMultiple),
        FieldPanel("meeting_details"),
    ]
```

**Comment by vsalvino** [comment]
Got it, yea that would be a bug.

Question... do you think it would be preferable to keep the Label above the Dropdown in the FieldRowPanel, or would it be preferable to have the Label next to the field as wagtail does it? I only ask because FieldRows tend to get a bit smashed/crowded when the inputs are not so short. I believe we had to do a lot of adjustments to labels and inputs because they would get way too smashed when streamfields start nesting (as in a typical `CoderedWebPage`)

**Comment by vsalvino** [comment]
Snippet page also has a couple issues. Checkbox column looks off being so wide. Plus the buttons in the header look less than ideal stacked instead of side by site (not sure if there is actually not enough room due to font size, or not).

Specifically for the checkbox, I know there is CSS somewhere that normalizes table column widths, I can't remember why, but I do remember that was implemented because some table was out of whack due to customization.

Wagtail:
![image](https://user-images.githubusercontent.com/13453401/50200784-739f3e00-0325-11e9-91df-bc6c8248e412.png)

CodeRed:
![image](https://user-images.githubusercontent.com/13453401/50200766-62eec800-0325-11e9-9a49-f4416d17fd65.png)

**Comment by FlipperPA** [comment]
I tend to default to what Wagtail does by default, and issue PRs upstream if it is something worth changing. I can see arguments to both sides: the FieldRowPanel is built to save space / avoid excessive scrolling when editing, but that puts horizontal space at even more of a premium. I'm +0 on leaving it the way it is in Wagtail, but perhaps putting the label above in a PR to Wagtail and seeing what the community thinks of the change.

**Comment by FlipperPA** [comment]
I also realize this would be significant work, but at some point, would it be worth removing `codered_admin.css` entirely, and then adding back the definitions that are still needed to pare it down to the bare necessities? I don't know the entire scope of your clients needs, so it may sound better to my ears than yours. :)

**Comment by vsalvino** [comment]
Yes, I mostly agree, the best approach would be to rebuild the CSS. Up until now we have not done much custom models/fields outside of stock coderedcms. Hopefully more bugs will pile on this thread to help identify what is needed and what isn't.
