### ISSUE TITLE
Form fields don't respect display order

### ISSUE THREAD

**Issue by FlipperPA** [coderedcorp/coderedcms#99]
I've created a form with two form elements:

"Your Email Address" or type email, display order 1.
"What Can We Do for You?" of type multi-line text, display order 2.

On the form itself, they are displayed in the reverse order: http://www.phillyaa.org/contact-us/i-need-help/

**Comment by vsalvino** [comment]
This is dependent on code in your local project. Our generated project template was fixed in 0.11 to create a default form model that respects order. See commit https://github.com/coderedcorp/coderedcms/commit/b3484e37d8ff0600b17e6a0bb78c4bd04780e798

Just add
```python
class Meta:
    ordering = ['sort_order']
```
to your model that inherits from `CoderedFormField`

On a separate note, form documentation is completely nonexistent in the docs.

**Comment by FlipperPA** [comment]
Beautiful, it worked!
